version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

  graphql-engine:
    container_name: hasura
    image: hasura/graphql-engine:v2.22.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    env_file:
      - ./hasura/.env
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata

volumes:
  db_data:
